version: "3.8"
services:
  adserver:
    build: .
    restart: always
    environment:
      NODE_ENV: production
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
